### ISSUE TITLE
Update to CouchBase lite 2

### ISSUE THREAD

**Issue by mathieumack** [mathieumack/MvvX.Plugins.CouchBaseLite#10]
The new version is already available :
https://github.com/couchbase/couchbase-lite-net

**Comment by borrrden** [comment]
If you have any questions feel free to ask.  I am a fan of the MvvmCross library

**Comment by mathieumack** [comment]
Will be done with the migration to MvvmCross 6 #12.
Migration started !

**Comment by mathieumack** [comment]
Hi @borrrden ,
After analysis, I think that, as mvvmcross 6 support .net standard, this repository will obsolete.
I will not do the migration to .net standard.
If I need to keep a mvvmcross plugin, I will do it in order to manage couchbase lite support platforms initialization (see : https://github.com/mathieumack/MvvX.Plugins.CouchBaseLite/tree/feature/12-mvvmcross_6).
What do you think ?

**Comment by borrrden** [comment]
Yes if you have a facility to auto call the activate methods then that is great. Otherwise you will need to delegate to the app. Starting in 2.6 the activate calls will become optional for all platforms except android as well (maybe iOS depending on device testing). Your analysis is correct about what needs to be done I believe.
